apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
      - name: taxi
        image: quay.io/kmcdermo/taxi
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: kmcdermo-pull-secret
