resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- files:
  - index.html
  name: www-files
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/part-of: taxi
