apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source-testing
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/bigkevmcd/taxi-stage-config.git
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: execute-gitops-task
spec:
  serviceAccountName: demo-sa
  taskRef:
    name: deploy-from-source
  inputs:
    resources:
    - name: source
      resourceRef:
        name: git-source-testing
    params:
    - name: NAMESPACE
      value: stage-environment
    - name: DRYRUN
      value: "true"
